//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 05:13:32 PM IST 
//


package com.ct.cql.elm.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.ct.cql.elm.model.AggregateExpression;


/**
 * The Count operator returns the number of non-null elements in the source.
 * 			
 * If a path is specified, the count returns the number of elements that have a value for the property specified by the path.
 * 
 * If the list is empty, the result is 0.
 * 
 * If the list is null, the result is 0.
 * 
 * <p>Java class for Count complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Count">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:elm:r1}AggregateExpression">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Count")
public class Count
    extends AggregateExpression
{


}
