//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.11 at 05:13:32 PM IST 
//


package com.ct.cql.elm.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Locator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Locator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="startLine" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="startChar" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="endLine" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="endChar" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Locator", namespace = "urn:hl7-org:cql-annotations:r1")
@XmlSeeAlso({
    CqlToElmError.class
})
public class Locator {

    @XmlAttribute(name = "startLine")
    protected Integer startLine;
    @XmlAttribute(name = "startChar")
    protected Integer startChar;
    @XmlAttribute(name = "endLine")
    protected Integer endLine;
    @XmlAttribute(name = "endChar")
    protected Integer endChar;

    /**
     * Gets the value of the startLine property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartLine() {
        return startLine;
    }

    /**
     * Sets the value of the startLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartLine(Integer value) {
        this.startLine = value;
    }

    /**
     * Gets the value of the startChar property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartChar() {
        return startChar;
    }

    /**
     * Sets the value of the startChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartChar(Integer value) {
        this.startChar = value;
    }

    /**
     * Gets the value of the endLine property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEndLine() {
        return endLine;
    }

    /**
     * Sets the value of the endLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEndLine(Integer value) {
        this.endLine = value;
    }

    /**
     * Gets the value of the endChar property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEndChar() {
        return endChar;
    }

    /**
     * Sets the value of the endChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEndChar(Integer value) {
        this.endChar = value;
    }

}
